$is_your_daddy = [
"Are your parents assholes? Because you're the shit.",
"Did your daddy write a dictionary? Because you put meaning in my life.",
"Does your father sell diamonds? Because you are FLAWLESS!",
"If you got those eyes from your mother, I know exactly why your daddy married her.",
"Is your daddy a boxer? Because you're one hell of a knock out!",
"Is your daddy a butcher? Because I want to bone you.",
"Is your daddy a car salesman? Because you have nice head lights.",
"Is your daddy a dentist? If yes, then open wide.",
"Is your daddy a doctor? Because you just cured my erectile dysfunction.",
"Is your daddy a donkey? Because you have a great ass!",
"Is your daddy a drug dealer? Because you sure are dope!",
"Is your daddy a genie because you're making my dreams come true.",
"Is your daddy a grocery store attendant because you have nice melons!",
"Is your daddy a hunter? Because your such a fox!",
"Is your daddy a jalapeno because you sure are hot.",
"Is your daddy a lock smith because you have the keys to my heart.",
"Is your daddy a magician? Because abracaDAYUM!",
"Is your daddy a photographer? Because I can picture us together.",
"Is your daddy a pilot because my heart taking off.",
"Is your daddy a pilot? Because you're FLY!",
"Is your daddy a sergeant because you're making my privates stand at attention!",
"Is your daddy a spandex salesman? Because you're TIGHT!",
"Is your daddy a terrorist? Because you are the bomb.",
"Is your daddy a thief? Because he stole all of the stars in the sky and put them in your eyes.",
"Is your daddy a traffic cop? Because you got fine written all over you.",
"Is your daddy a welder, because you know how to mend my broken heart!",
"Is your daddy a wrestler? Because I just want to take you down.",
"Is your daddy an alien? Because you're out of this world.",
"Is your daddy an Aquafina worker? Because your jugs are perfect.",
"Is your daddy an artist? Because you're a fine piece of work.",
"Is your daddy an astronaut? How did you get those stars in your eyes?",
"Is your daddy an electrician? Because you are so electrifying.",
"Is your daddy the owner of Wendy's because you make me want to eat great even late!",
"Is your daddy Tony The Tiger because you look gggggreat!",
"Is your daddy Willy Wonka because you look delicious.",
"Is your mom a hooker? Because I'm hooked on you.",
"Was your daddy a bricklayer? Because you have one hell of a foundation.",
"Was your daddy a leprechaun, because Irish you were naked.",
"Was your daddy a mechanic? How did you get such a finely tuned body?",
"Was your father a meat burglar? Because someone stole two fine hams and shoved them down the back of your pants!",
"Your daddy must be a cheeseburger, because I could nom you all night long.",
"Your daddy must be a high jumper, because you make my bar raise!",
"Your daddy must be an archer, because he sure shot a bullseye.",
"Your daddy must have been a baker, because you got the nicest set of buns I've ever seen.",
"Your daddy must play the trumpet, because you're making me horny!"]

$harry_potter = [
"Baby, are you the Nimbus 2000 cause you're sweeping me off my feet!",
"Baby, you don't need defence against my dark arts.",
"Are you a dementor? Because you take my breath away.",
"Can I Slytherin your Ravenclaw or would you rather Hufflepuff my Gryffindor?",
"Come here, I'll show you a REAL Patronus.",
"Come on, let's do it Hippogriff style!",
"Did you just say Wingardium Leviosa? Cause you've got me rising, baby.",
"Did you survive Avada Kedavra? Because you're drop dead gorgeous.",
"Hagrid's not the only giant on campus, if you know what I mean.",
"Have you heard of Platform 9 and 3 Quarters? Well, I can think of something else with the exact same measurements.",
"I am a seeker, are you my golden snitch?",
"I don't have a broom, can I ride yours?",
"I may not be Harry Potter, but I can be your chosen one.",
"I was the one who gave Moaning Myrtle her nickname!",
"I would take a marauders map just to stare at you all night!",
"I'd like to get my basilisk into your chamber of secrets.",
"I'll remember to protect my wand when entering your chamber of secrets!",
"I'm not wearing an invisibility cloak, but do you think I could still visit your restricted section tonight?",
"Interested in making some magic together? My wand is at the ready.",
"Is that a wand in your pocket or are you just happy to see me?",
"Just the thought of your wand makes me spill my potion!",
"Let me Slytherin your Griffendoor.",
"Mind if I Weasley my way into your conversation?",
"My house is called the Shrieking Shack for a reason. I'll show you tonight.",
"My love for you burns like a dying phoenix.",
"My name might not be Luna, but I sure can Lovegood.",
"My wand has chosen you!",
"Once you go black you siriusly don't go back!",
"One night with me and they'll be calling you MOANING Myrtle.",
"Save a broom, ride a Quidditch player.",
"Screw Gryffindor, Ravenclaw, Hufflepuff and Slytherin, the only house I wanna be in is yours.",
"Speak Parseltongue to me and I'll let my snake out!",
"Wanna explore my chamber of secrets?",
"Wanna make me moan like Myrtle?",
"Want to learn to speak troll? Don't worry I can get you grunting in no time.",
"We may not be in professor Flitwick's class, but you sure are charming!",
"Let's go look for the Room of Requirement.",
"Would you like to whomp my willow?",
"You can have the portkey to my heart.",
"You don't need to say Incendio to light my fire.",
"Come with me and you'll see love spells. Go with her and you'll see HogWARTS!",
"You make my Huffle puff.",
"You must be magical, because I've fallen under your spell.",
"You must be my horcrux, because you complete me.",
"You must be really good at Transfiguration, Because you've changed my life.",
"You must have given me some Skelegrow, because my bone is really growing right now.",
"Your name must be Severus Snape, because you're making my prince full blood.",
"Your smile's like expelliarmus, simple but disarming.",
"C'mon Baby Light My Fire."]

$star_wars = [
"Are you related to Yoda? Because yodalicious.",
"Can I call you my Naboo?",
"Can I see your garbage mashers on the detention level?",
"Captain, being held by you is quite enough to get me excited.",
"Did it hurt when you fell from Cloud City?",
"Did you know the French say orgasms are like little death stars?",
"Do you understand the binary language of moisture vaporators? Because I’d like to program your binary loadlifter.",
"Don't worry baby, if I get tired there are 3 million more of me.",
"Honey, you’ve been looking for love in Alderaan places!",
"How can you be from an ice planet when you’re so Hoth?",
"I am C3PO Human cyborg sexual relations.",
"I could get you undressed in less than 12 parsecs.",
"I could spend a millennium in your falcon.",
"I did the Kessel run in under 12 parsecs but I'm gonna take it slow with you.",
"I farm moisture for a living.",
"I feel a great disturbance in my pants.",
"I hope you’re into cyborg human relations, because I’m feeling like a machine right now.",
"I know what you’re thinking. That’s no moon, that’s a space station!",
"I may look like an Ewok, but I’m all Wookie where it counts, baby.",
"I must be from Alderaan, because you just blew up my world.",
"I usually Han Solo, but I'd let you turn on my lightsaber!",
"I wanna Lando in your Calrissian.",
"I want you so bad we should get matching Tatooines.",
"I would hit that like the side of a tree on Endor.",
"I'm here to collect the bounty on dat ass.",
"If you think Chewbacca is hairy, wait until you see my wookie!",
"Is that a lightsaber in your robe or are you just happy to see me?",
"Leia's buns ain't got nothing on yours, baby.",
"Let's get hoth and heavy.",
"Many Bothans died so we could do naughty things.",
"Nice buns, Princess! On your head, that is.",
"ObiWan told me to follow my instincts, and my instincts are all over you.",
"Open up your hangar, my starfighter needs refueling.",
"Size matters not.",
"The force is strong with this one.",
"Unlike Han, I won't shoot first.",
"Wanna see my lightsaber?",
"Want to spend the night inside my tauntaun? I promise it doesn't smell worse on the inside.",
"Why don’t we head to my bedroom, peel back my Star Wars sheets, and discover what a true Jedi can do with his lightsaber?",
"Yoda one for me.",
"You like Star Wars? Let's go back to my place and violate the Jedi Code.",
"You look strong enough to pull the ears off a gundark.",
"You stole my heart like the rebels stole the Death Star plans.",
"You're the droid I've been looking for.",
"You're the ObiWan for me.",
"Your smile glows brighter than a lightsaber."]

$gyms = [
"Are you a high jumper because you make my bar go up.",
"Are you from Tennessee? Cause you're the only ten I see!",
"Are you using that adductor machine so you can crush me between your thighs later?",
"Are your legs tired? You have been running in my mind all day.",
"Can I get your jersey, name, and number?",
"Can you close the bracelet for me?",
"Can you teach me how to use this machine?",
"Did you fart? Because you just blew me away!",
"Did you hear the latest health report? It said you're supposed to increase your intake of vitamin ME.",
"Do you believe in love at first set? Or should I curl this barbell another 10 times?",
"Do you have a band aid? Because I'm cut!",
"Do you have a map? I just keep on getting lost in your eyes.",
"Do you have any tape? Because I'm totally ripped.",
"Do you know any workout to reduce breast size? Mine is a bit too big to handle.",
"Do you know karate? Because your body is really kicking.",
"Do you squat here often?",
"Do you want me to spot you while you do those lunges?",
"Do you work at UPS? Because I saw you checking out my package.",
"Don't go to the zoo today, because the pythons are out.",
"Excuse me, but I think I dropped something! My jaw.",
"Girl, do you need to get your protein macros up? Because I'd gladly share a meat platter.",
"I heard you're into fitness. How about fitness this in your...",
"You make working out look good!",
"Going to a sculpture class won't even get you this chiseled.",
"Hey baby are you a boxer? You should because you're one hell of a knock out!",
"Hey baby, how much does a polar bear weigh? I don't know, but it broke the ice.",
"How'd you like to be my special push up partner?",
"How'd you like to go on a long romantic walk on the treadmill?",
"I got stopped at the airport last week for trying to bring these guns onto an airplane.",
"I got stopped by a police officer on the way here. He told me it was illegal to carry these guns in public.",
"I have more MASS than a church on Sunday!",
"I hear you're thirsty! I've got a six pack right here.",
"I hope you know CPR, because you take my breath away.",
"I hope you took your Flintstone vitamins today because I'm gonna make your Bedrock!",
"I know a fun activity that can burn 500 calories an hour.",
"I never do this, but I think you're cute and I got tired of waiting for you to talk to me.",
"I wish this gym had a stationary bike built for two.",
"I'm afraid that I have to ask you to leave. Your sexy body is making other guys here look really bad.",
"I'm gonna have my whey with you!",
"I'm too flexy for my shirt.",
"Is your tank top felt? Would you like it to be?",
"Let's do lunge.",
"Me without you is like a sneaker without laces.",
"My feelings for you are like diarrhea, I can't hold it in!",
"My personal trainer said I have to come over and talk to you for five minutes as part of my routine.",
"Seeing that you're new here, let me show you where the water fountain is...the next drink's on me.",
"Sex burns 300 calories per hour, wanna exercise?",
"That stairmaster isn't the only thing getting my heart rate up.",
"We should train together, I've heard it's good for bone density. And I don't just mean my skeleton.",
"What has 145 teeth and holds back the Incredible Hulk? My zipper.",
"What says we head over to GNC for a bottle of human growth hormone?",
"You don't need to waste your time on that treadmill, you've been running through my mind all day.",
"Your dad must be a baker, you've got hot buns."]

$coffee_shops = [
"That's a nice mug you got on ya.",
"Affogato where I am when I'm with you.",
"Are you from Starbucks? Because I like you a latte.",
"Bean Mine.",
"Can I buy you a coffee sometime?",
"Can you watch my laptop for a minute? I'll buy the next round of coffee.",
"Careful of that Earl Grey, it’s super hot! Oh wait, you don’t need to worry. It’s not as hot as you.",
"Do you get a hint of almond in this Keemun? No? That’s odd, because I’m nuts about you.",
"Do you make your own kombucha? Because those probiotics are doing your body good.",
"Do you prefer French Press or Bialetti for your morning coffee?",
"Excuse me, but my Chai gave me an awful tongue burn. I think I need mouth to mouth.",
"Excuse me, miss, things are about to get real steamy in here.",
"Giving me your number sounds like a fair trade.",
"Hello there, how do you brew?",
"They call me coffee, because I grind so fine.",
"Hey girl, are you a chai because I’d like to get dirty.",
"Hey boy, are you a faulty French press because I'd like to be burned by you and recall you afterwards.",
"Hey there, did someone request a little extra whip?",
"Don’t add honey to that chamomile. You’re already too sweet.",
"Hey, I just met you, and this is crazy, but here's my number, so caramel maybe?",
"Hey, if I bought you a drink would you let me sit here for several hours and work on this screenplay?",
"Hey, wait, give me another shot!",
"Hey, was your daddy a barista? Because you are almost what I ordered.",
"There seems to be a kiss of mint in this blend. How about a real kiss, just to be sure?",
"Hold the sugar please, you're sweet enough for the both of us.",
"I can feel something brewing between the two of us.",
"I have a personal rule to never eat chocolate alone.",
"How you can look so great pre coffee.",
"I like my baristas like I like my coffee. Hot, sweet, and creamy.",
"I like my coffee like I like my men. Tall with a confusing Italian name.",
"I like the way you espresso yourself.",
"I like you as much as I like a Pumpkin Spice Latte, which is to say I love you forever, let’s get married.",
"I love the way you espresso yourself.",
"I think I'd want nutritionist approved bacon coffee.",
"I'm going to start watching my caffeine intake, because you make my heart palpitate, baby.",
"I'm pretty sure the last 10 books I've read have all been in coffee shops. I don't even know if I'm literate at home anymore.",
"I'm soy into you.",
"If I were a singer songwriter, my ultimate goal would be to inspire novelists in coffee shops.",
"If you were coffee grounds, you'd be espresso because you're so fine.",
"Java number I can call you at?",
"Just promise you won't tamper with my heart.",
"My coffee hasn't kicked in yet, so I can't think of a charming pickup line.",
"My coffee is really hot. But you're hotter.",
"The barista may have forgotten your name, but I sure haven't.",
"Wow, two teaspoons? Lucky for you, I’m a pretty good spooner myself.",
"You mocha me crazy!",
"You roast my heart!",
"You're like my coffee, you keep me up all night.",
"You're such a TEAse.",
"You've turned me down before but I'm asking for an extra shot.",
"You’re like this year’s Darjeeling. Had me at first flush."]

$dog_parks = [
"A day with you is like an eternity of behind the ear scratches.",
"Are you tired? Because you've been running through my mind all day with a frisbee in your mouth.",
"Can I get you a tennis ball?",
"Can you help me find someplace to pee?",
"Come on, don't make me beg!",
"Dog heaven must be missing an angel.",
"Girl, you are so FETCH.",
"Have your people call my people.",
"Haven't I sniffed you someplace before?",
"Hey girl, you're one fine looking mother pupper.",
"Hey baby, want to help me bury my bone?",
"How about we ditch these leashes and go for a run?",
"I am looking for a leash free relationship.",
"I came here looking for a little tail.",
"I don't bite unless it's called for.",
"I don't normally pick up at the park. Unless it's number two.",
"I love Squirrel.",
"I love seafood, and your breath smells like crab cakes.",
"I love to be pawed.",
"I must be behind on my vaccines because I am love sick.",
"I smelled you down the street, and my nose brought me right to you.",
"I want to have your litter of puppies.",
"I'd never keep you on a short leash.",
"I'll be your lady if you'll be my tramp.",
"I'm a poodle in the streets, but a bulldog in the sheets.",
"I'm looking for a no leash attached cuddle buddy.",
"I've crossed all the dog parks in the world to find you.",
"Iams so in love with you.",
"Is it warm out here, or are you in heat?",
"Is that pug making goo goo eyes at me?",
"Is that your dog's tail wagging or are you just happy to see me?",
"It was love at first sniff.",
"Need rescuing?",
"Roll over. I'll scratch your belly.",
"Roses are grey, violets are grey, everything is grey when you're a dog.",
"Since chocolate is toxic to dogs, how about a little sugar?",
"Sniff my butt. It's the quickest way to my heart.",
"Sorry, baby. I thought it was hump day.",
"Stay.",
"That fire hydrant might be fake, but you are real pretty.",
"There's not a crate strong enough in the world to keep me from you.",
"Your dog is beautiful. I see it takes after its owner.",
"What says we take this discussion off leash?",
"With the size of your paws, you can mark my territory any day of the week.",
"You came back to this dog park to see me, didn't you?",
"You come here often?",
"You had me at ruff.",
"You make me want to be a more obedient dog.",
"You want to play tug of war sometime?",
"You. Me. Bacon.",
"You're a great catch.",
"You're all bright eyed and bushy tailed.",
"You're more fetching than my dog's favorite ball.",
"You're pawfect.",
"Careful, my bark is contagious.",
"Your doghouse or mine?",
"Can I hibermate with you through the Ice Age?",
"Don’t let my tiny arms fool you.",
"Girl, you must be a fossil sample and I must be an impatient palaeontologist, because I want to date you badly.",
"Hey Baby, I wanna see your bedrock!",
"BC stands for Before you Came into my life.",
"I know how to plesiosaur a man.",
"Let’s forget the carbon and move straight to the dating!",
"Let’s have some tyrannosaurus sex.",
"Wanna yabba dabba do it?",
"We should carbon date because our half life would approach eternity.",
"Why did you have to end the Ice Age by being so hot?",
"You are dinomite!",
"You as hairy as a mammoth, and it is really turning me on!",
"You bring out the caveman in me.",
"You know what they say about a man with a large crest.",
"You know what they say about brachiosaurs. The neck’s not the only thing that’s disproportionately long.",
"You put the ass in Jurassic!",
"You should come home with me, because I’ll make you dino sore.",
"You’re the triceratops!"]

$beaches_pools = [
"All those curves, and me with no brakes.",
"Are you a low interval sprint set? Because you're making my face all red.",
"Are you the deep end? Because I’m ready to dive right in.",
"Are you the splash and dash, because you've got my heart beating.",
"Can I see your tan lines?",
"Can I swim in your eyes on a hot summer day?",
"Can you call a lifeguard? Because I'm drowning in your eyes.",
"Come on, I'm a wealthy neglected housewife, you're a pool boy. It's practically required by law that we do it.",
"Could you watch my stuff while I go for a swim? ",
"Dang girl! You must look extra fine with that glowing tan.",
"Do you believe in love at first sight, or should I walk by again?",
"Do you have a sunburn, or are you always this hot?",
"Do you have any sunscreen? Because you are burning me up!",
"Do you have swimmers as good as China? We'll have to do something about that.",
"Do you want to see my snake on the beach?",
"Don't save me just yet. Just a little more mouth to mouth.",
"Excuse me, do I need to buy a ticket for your fantastic voyage?",
"Girl, you give me the butterflies.",
"Hear that? The ocean wants you to join me for a drink.",
"Hey baby, the sun isn't the only thing that rises.",
"Hey baby! Can you please cover up your hot body cause the sun is melting and it is getting hot here.",
"I'd swim across the ocean just to see you smile.",
"I'd swim up to 800 meters for your love.",
"Is your name 400 IM? 'Cause you took my breath away.",
"Lane lines can't keep us apart.",
"You make my heart flutter kick.",
"Which way to the beach?",
"Hey little princess. I’m just doing squats on the beach and need someone to come count them.",
"Hey sexy! The sun isn’t the only thing that rises.",
"Hey, wanna go take a walk on the beach and watch the earth rotate while the sun goes out of view?",
"Hey, you were great on Baywatch last night!",
"How was your last skinny dip? I bet I can make your next one better.",
"I barely noticed you in the winter months.",
"I can't swim! Can I hold on to your floaties?",
"I could put some motion in your ocean.",
"I don't know which is prettier today, the water, the sky or your eyes.",
"I feel like I'm in Scandinavia, because when I'm with you its's like the sun never sets.",
"I hope you know CPR, because you are taking my breath away.",
"I like your braces. They shine against the waves.",
"I must be lost. I thought paradise was further south.",
"I never have a false start.",
"I noticed you thrashing around. Would you like to hold onto my floaties?",
"I perform best when I'm wet.",
"I really like your suit.",
"I seem to have sand in my bathing suit, wanna get it out?",
"I was looking for treasure and I think I found some.",
"I forgot my towel, can I share yours?",
"I'll show you my tan lines if you show me yours.",
"I'm a love pirate, and I'm here for your booty! ARRRGGGHHH!",
"I'm drowning in the sun and need mouth to mouth now!",
"I'm not a very good swimmer, do you have any lifeguard experience?",
"I'm worried about you getting a sunburn. How about I cover you with sunscreen?",
"I've never won gold in the breast stroke, but that could all change tonight.",
"I’m afraid I’m going to have to ask you to leave, you’re making the other guys look really bad.",
"I’m new at the complex, can I have directions to your apartment?",
"I’m not a CPR dummy, but I’d let you practice some mouth to mouth.",
"If everybody here accidentally drowned, the first bloated corpse I'd pull out would be yours, sweetheart.",
"If someone throws sharks in the water, I'll save you first.",
"If you got out with me, I can get you Michael Phelps phone number.",
"If you were a beach, I’d pick you to lay on.",
"Ignore the ray bans. There is nothing shady about me.",
"Is it hot out here, or is it just you?",
"Is your name Summer? Because you are hot!",
"Just like the Summer, I bring the heat!",
"Let’s go back to my place and get out of these wet clothes.",
"Man, you have to be a swimmer, because you blow everyone else out of the water with your good looks!",
"Nice beach balls, can I play?",
"Now how did you manage to fit that great big thing into that little old Speedo?",
"People tell me I have a good breaststroke, but I'd say I'm a pretty good swimmer too.",
"So you're a mermaid huh? I take it you are very accustomed to sea men then?",
"So… did you hear how I saved that little girl from drowning last month?",
"Sorry, babe, did I make you all wet?",
"That bathing suit would look a lot better on the floor next to my bed.",
"That sure is a lovely set of lungs you are wearing today.",
"They called me the human torpedo even before I took up swimming.",
"Wanna come jump in the pool with me? Because you just caught me on fire.",
"Wanna go back to my place and do something about that shrinkage?",
"Wanna join the 9 foot deep end of the pool club?",
"You know, they call it adult swim for a reason.",
"You look like you could use some help rubbing in that tanning oil.",
"You make my heart melt like ice on a beach.",
"You make my heart slip and slide.",
"You really flip turn me on.",
"You're like the anti fog spray for my goggles, you just brighten up my day. ",
"You're so hot, the sun is jealous.",
"You've got the fanciest fantail I've ebber seen.",
"Your eyes are bluer than the Atlantic Ocean, and I'm lost at sea.",
"Your eyes are like a sunset, they are beautiful, inspiring, and hard to turn away from.",
"Your nickname should be Pool Tile because you’re slippery when wet.",
"Your skin is burning like my heart."]

$computers = [
"A life without you would be like a computer without an OS.",
"Anonymity makes me even more handsome.",
"Are you a computer keyboard? Because you're my type.",
"Are you a computer whiz? You know how to turn my software to hardware.",
"Are you a decimal number? The thought of you always floats inside my head.",
"Are you an angel, because your texture mapping is divine!",
"Are you an applet? You make me feel all GUI inside.",
"Are you an exception? Let me catch you.",
"Are you my driver? Because you make my life worthwhile.",
"Are you sitting on the F5 key? Cause your ass is refreshing.",
"Are your pants a compressed file? Because I'd love to unzip them!",
"My mother doesn't have a Facebook account. If we take this thing to the next level, you wouldn't have to worry about rejecting her friend request.",
"Baby are you a motherboard?, because RAM.",
"Baby you know this junk isn't USB 2.0, it's firewire!",
"Baby you must be Google Glasses, because you augment my reality.",
"You're so cute you made my page 404.",
"Baby, if they made you in C, you would have a pointer to my heart.",
"Baby, if they made you in Ruby, you'd be the object of my desire.",
"Baby, there is no part of my body that is Micro or Soft.",
"Baby, you make my floppy disk turn into a hard drive.",
"Baby, you must be running a TCP protocol, since every time I talk to you, your body gives me an acknowledgment!",
"Baby, you overclock my processor.",
"Be the hard drive of my dreams.",
"Before you, I was a PC without a power outlet.",
"Can I stick my USB drive in your USB port?",
"Can you be my ActionListener? That way you notice everything that I do.",
"Can you be my private variable? I want to be the only one with access to you.",
"Come to my I.P. address and I’ll give you sudo access.",
"Computer techs have skilled fingers if you know what I mean.",
"Could I have your I.P?",
"Do you think we can make it serious and disable network sharing?",
"Don't worry honey, they call it my dual channel RAM.",
"Don't worry, the first couple of times it's always Abort, Retry, Fail.",
"Every once in a while two numbers meet, link, and become forever binary.",
"Girl, are you WiFi? I'm feeling the connection!",
"You are hotter than the bottom of my laptop.",
"Hey baby, did you know I am wearing a C String?",
"Hey baby, I'm a power source, and you're the kind of resistor i'd like to deliver my load to.",
"Hey Baby, Let me hack your kernel.",
"Hey baby, let's turn off our firewalls and connect our Ethernet cable.",
"Hey cutie! I have a processor, got an empty slot on your motherboard?",
"How about I take off your cover and insert a bigger CPU.",
"How about we do a little peer to peer saliva swapping?",
"How about we go home and you handle my exception?",
"How'd you like to come to MySpace so I can Twitpic your Yahoo until you tweet my Tumblr and I Google all over your Facebook!",
"I am a boolean method whose love will always return true.",
"I am a Buffered Reader. You input meaning into my life.",
"I am the field attribute in your class, I can't exist unless you do.",
"I didn't mean to ogle you, but I'd sure like to Google you.",
"I googled your name earlier. I clicked on I'm Feeling Lucky.",
"I had to drop out of college because the $250,000,000 software company I started in my dorm room was taking up too much of my time.",
"I hope you're an ISO file, because I'd like to mount you.",
"I must be using Apple maps, because I keep getting lost in your eyes.",
"I need to hop over to Facebook for a second to change my status to smitten.",
"I output gibberish as you tap my keypad.",
"I think we should increase our bandwidth.",
"I think you could be an integral part of my project life cycle.",
"I think you're my compiler. My life wouldn't start without you.",
"I want all of our functions to be read write.",
"I was hoping you wouldn't block my pop up.",
"I wish to uncompress you over all my disk space.",
"I wish you were Broadband, so I could get high speed access.",
"I would love to stick my pins into your sockets.",
"I'd ask if you come here often, but I already stalk you on FourSquare.",
"I'd get a T3 to watch your streaming video.",
"I'd like to play on your laptop.",
"I'd switch to a Iphone for you.",
"I'd switch to emacs for you.",
"I'll always have cache for you.",
"I'll bet my hard drive is the biggest you've ever seen.",
"I'll have to try again tomorrow, because you've already exceeded my bandwidth.",
"I'm definitely in the range of your hotspot. How about you let me connect and get full access?",
"I'm overheating because you're stuck in my head like an infinite loop.",
"I've fully rebooted from my last relationship.",
"If I was an operating system, your process would have top priority.",
"If I were a method, you would be my parameter, because I will always need you.",
"If I were an assembly language, I'd jump to your address, shift right a bit, push it in, pop it out, load a byte into your accumulator, then jump if you're negative.",
"If I were an operating system, your process would be real time priority.",
"If we were connected on Linkedin, I'd endorse you all night long.",
"If you ever need to get rid of a trojan, don't hesitate to call me!",
"If you have an empty slot, I have the card to fill it.",
"If you were a part of my domain, we could share cookies.",
"If you were a USB Port I'd stick my jump drive into you.",
"If you were a web browser, you'd be called a Firefoxy lady",
"If you were an Ebay auction, I'd totally buy it now.",
"If you were an ISP I'd dial you all day long.",
"If you won't let me buy you a drink, at least let me fix your laptop.",
"Im not staring, Im stuck in a loop while girl equals hot.",
"Is your name Google? Because you have everything I've been searching for.",
"Is your name Wifi? Because I'm really feeling a connection.",
"Is your network encrypted? Im looking to hack.",
"Isn't your email address beautiful girl at my dreams dot com?",
"Let's interface our hardware.",
"Let's just cut to the chase, I wanna hotsync your PDA.",
"Living with you would be like living in a virtual reality.",
"Mind if I run a sniffer to see if your ports are open?",
"My up time is better than BSD.",
"My attraction for you is stronger than the magnetic forces inside of my hard disk.",
"My love for you cannot be measured with an integer, not with a float, and not even with an array. It is out of bounds and infinite.",
"My love for you comes with no strings attached.",
"My love for you is a constant variable. Unchangeable.",
"My love is a for loop without the increment operator. Infinitive, non terminating, and difficult to stop once it starts running.",
"My servers never go down, but I do!",
"Need me to unzip your files?",
"Nice Set of Floppies!",
"No GPU in the world could make you look hotter than you already are.",
"No kinky Windows stuff.",
"No matter how I sort things, you'll always be first.",
"Nobody turns me on from a cold boot like you.",
"Oh little processor of my desire!",
"Our Love Routines link perfectly.",
"Press any key to continue.",
"Public class Your World extends My World.",
"Roses are FF0000, violets are 0000FF. All my base are belong to you.",
"There is no cache, let's go straight to the hard drive.",
"There is no primitive data type that could possibly hold the number of things I would do to spend one night with you.",
"Trust me, I'm user friendly.",
"We are an aggregation of classes. One cannot exist without the other.",
"We can make beautiful wav files together.",
"WebMD says your love is contagious.",
"Well, if that's how you feel, I guess it's time to upgrade.",
"[Well, now you've gone and killed my process.",
"What do you say we play a game of Words With More Than Friends?",
"What's a nice girl like you doing in a chat room like this?",
"What's the difference between a crush and a Facebook account? I'm not rapidly developing a Facebook account on you.",
"Where's the like button for that smile?",
"Why don't you come down to my apartment in my mom's basement sometime?",
"Would you like to enjoy my laptop? I promise I don't have any viruses.",
"You are a field in my class. You will always be protected.",
"You are my API. I want to know everything about you.",
"You are my increment operator. You make my value increase.",
"You are my initializer. Without you, my life would point to nill.",
"You are my loop condition. I keep coming back to you.",
"You are my methods. I am nothing without you.",
"You are my semicolon. Always present in everything I do.",
"You are my superclass. You define what I can do.",
"You are so hot, I reached a runtime error.",
"You are the Apple of my iMac.",
"You are the IDE of my life. I find it easier because of you.",
"You are the Java Development Kit in my life. I won't compile without you.",
"You auto complete me.",
"You defragment my life.",
"You got me stuck on Caps Lock, if you know what I mean.",
"You had me at Hello World.",
"You have nice syntax.",
"You look familiar. What's your Twitter handle? I think I follow you.",
"You make me want to calibrate my joystick without the latest drivers.",
"You must be tired because you've been streaming through my RSS feed all day.",
"You must be Windows 95 because you have me so unstable.",
"You put the SPARC in my workstation.",
"You still use Internet Explorer? You must like it nice and slow.",
"You totally spiked my traffic.",
"You want to learn about computers? You've already passed the first lesson, turning me on!",
"You're making me feel like I have something in common with these pop up ads.",
"You're so pretty, I wouldn't even need to use an Instagram filter if I took your photo.",
"You've stolen the ASCII to my heart.",
"Your beauty rivals the graphics of Call of Duty.",
"Your beauty rivals the graphics of MW3.",
"Your eyes are far more gorgeous than any source code I have ever seen.",
"Your homepage or mine?",
"YouTube Myspace and I'll Google your Yahoo!"]

$political_events = [
"Are you a pilgrim? Because I'd let you land on my rock.",
"Are you a union worker with a history of anarchy?",
"Are you in charge of the new transportation bill because you have been running through my mind all day!",
"Are you the manhattan project? Because you're the bomb.",
"I'll make you see stars and stripes, baby.",
"Baby, you have more curves than the Democratic Party line.",
"Call me John Adams, because I want to be all up in your XYZ affair.",
"Call me Paul Revere because I'd like to give you a midnight ride.",
"Do you want to see a majority whip?",
"Excuse me but I'm looking for weapons of ass destruction",
"The agricultural adjustments act couldn't keep me from plowing your field.",
"Good thing I'm not a colonist, because I'd let you do intolerable acts to me.",
"How would you like to take a ride on Air Force One?",
"I asked Barack Obama if you and I could get together later, and he said Yes, you can.",
"I don't need a CRS report to tell me how beautiful you are.",
"I have sex like I fight wars. I have no exit strategy.",
"I may not be the POTUS, but I see US on TOP of each other.",
"I motion to elongate the caucus.",
"I must be the Russian space program, because I'm just dying to launch my Sputnik.",
"I think you should remove all barriers to imports, it will ease my inflation and the benefits will trickle down.",
"I want to do to your body what Mitt Romney does to poor people.",
"I'd like to get your opinion on my poll.",
"I'd love to have a discussion with you about Bush, Dick, and Colin.",
"I support the motion to have you come back to my place for some bipartisan outreach.",
"I'm like the Vietnam War, way longer than you thought I'd be.",
"I've got a stimulus package waiting for you.",
"I'm so glad prohibition was repealed, because I'm drunk on you.",
"If you were a president, you'd be Baberaham Lincoln.",
"Just ask Thomas Paine, he knows dating me is common sense.",
"Let's make like Carnegie and horizontally integrate.",
"My names Huey Long and I can share some wealth",
"I couldn't handle it if there was a tax on your sugar.",
"Oh, we can filibuster all night long.",
"On a scale of one to America, how free are you tonight?",
"The battle of the Bulge? No competition.",
"The Gettysburg Address was short, but I know something that isn't.",
"The national debt isn't the only thing that's rising.",
"Let's caucus together sometime.",
"You know what's unconstitutional? The fact that you still have every article of clothing on.",
"You may not be my First Lady, but I'll make you feel like Jackie OH!",
"You must be John Locke, because you are the key to my conscious.",
"You'd make a great vice. Want to be my running mate?"]

$bars = [
"Remember the time we made out in the parking lot 15 minutes from right now? ",
"And I thought the beer was good here!",
"Are you busy at last call?",
"Can I ask you a personal question? Beer or wine?",
"Can I buy you a drink so we can tell each other lies?",
"Can you drive me home, I'm too drunk to drive and you wouldn't want me to get a DUI would you?",
"Could I buy you a drink?",
"Did it hurt when you fell from Heaven?",
"Did we go to high school together, or do you look familiar because I'm already in love with you?",
"Did you have Mrs. O'Brien for 8th grade English class? No? Me neither! We have so much in common.",
"Did you steal my beer? That one looks just like the one I was drinking.",
"Do you come here often?",
"Do you like blow jobs or sex on the beach? I'm talking cocktails of course.",
"Do you like rock & roll music? Well, good because I'm going to rock your world.",
"Do you think most men that go to nightclubs and bars are jerks?",
"Do you want a drink? Yes? Me too, please give me a double whiskey, 5 shots of tequila and a large beer.",
"Do you want to dance?",
"Don't you just hate it when people try to use pick up lines on you?",
"Excuse me, why is your drink glowing?",
"Here's 50 dollars. Drink until I'm good looking and then come talk to me.",
"Hey cutie, your next drink's on me. I've saved a lot of money because I'm still on my parents phone plan. ",
"Hey! You owe me a drink. I dropped mine when you walked by.",
"I just wanted to tell you that I love the way you dance.",
"Hi, I'm Brad Pitt. I'm wearing a disguise so I won't be recognized. May I buy you a drink?",
"High school yearbooks kind of remind me of wedding albums. I'm not married.",
"I couldn't help noticing that you're drinking the same thing as me. Are you trying to copy me?",
"I definitely know you from somewhere, I wouldn't have forgotten you.",
"I don't have a yacht, but I have over 100 Twitter followers.",
"I hate singles bars. How about you?",
"I have a 401K now. That's a type of blood condition, right?",
"I just moved here. Want to show me around the area?",
"I lost my phone number. Can I have yours?",
"I see you got some tequila.  Does that mean you wanna give me a shot?",
"I think all the bottles in this bar must be jealous, your beauty is the most intoxicating thing here.",
"I'm bored. If you will entertain me, I will buy you a drink.",
"I'm letting people take body shots off my amazing torso for 5 dollars. How many can I count you in for?",
"I'm not drunk. I'm just intoxicated by you.",
"I've been to jail so much less than everyone else we went to school with.",
"If being hot was a crime, you'd be guilty as charged!",
"If I'd have known I'd see you here, I'd have been sitting on this bar stool since my 21st birthday.",
"In medieval times, my beer belly would be a sign of prosperity and attractiveness. What do you think?",
"Is it hot in here or is it just you?",
"Lemme Buy You A Drank. Remember T Pain?",
"Look, I'm just trying to drink here, and you're very distracting.",
"Most people are intimidated by me. It's okay, you don't have to be scared to buy me a drink.",
"My aunt died and left me six million dollars with the stipulation that I find a wife by Friday.",
"My drink is getting lonely, bring yours over.",
"Of all the gin joints, in all the towns, in all the world, you walked into this one. ",
"See that table over there? I've been waiting for you to come over and talk to me.",
"I could buy you a drink, but I'd be jealous of the glass.",
"That outfit is horrible, it would look better on my bedroom floor!",
"There's a roaring romantic fire back at my place. Would you like to go get warm?",
"This isn't a beer belly, it's a fuel tank for my love machine.",
"What do you say I buy the booze and you show me how to shake it.",
"What do you say we get out of here? I bet you're way better to wake up next to than a hangover.",
"What's a sweet and lovely thing like you doing in a place like this?",
"What's your favorite song to dance to?",
"What's your favorite radio station to listen to?",
"What's your name, besides beautiful?",
"What's your sign?",
"I hope you don't mind me stopping you, but I just had to meet you.",
"When you're done with that beer let's play spin the bottle.",
"Would you girls like to go party over at my place?",
"Would you like to dance with someone ugly?",
"You are the special someone I have been saving this seat for.",
"You're like a turkey in the oven all day. Just getting hotter and hotter.",
"Do you believe in love at first sight or do you want me to walk by again?",
"Hey baby, let's play “carpenter.” First we get hammered then I nail you!",
"Hey, we have genitalia, we should converge in sexual intercourse.",
"How about you swing by my place so we can do some complex algebraic functions.",
"I looked up beautiful in the thesaurus today and your name was included.",
"I may not be a genie, but I can make your dreams come true.",
"I put the STD in STUD, now all I need is U.",
"I'm craving some bacon, wanna strip?",
"If you were a booger, I'd pick you first.",
"I hope your name isn't Macaulay Culkin, because you're not going home alone.",
"If I could rearrange the alphabet, I'd put U and I together.",
"Can I kiss the most beautiful girl at the whole party? ",
"Those must be space pants, because your ass is out of this world.",
"Hey, are you a gust of wind? Because you blow me away!",
"You must have a large mass because I am highly attracted to you.",
"You want to sleep with me and I want to sleep with you. I'm at least half right.",
"You're hot, I'm ugly. Let's make average babies.",
"You're one in a million. That means there are roughly 7,000 people exactly like you in the world.",
"You're so hot you melt the plastic in my underwear.",
"Your clothes are making me uncomfortable, take them off."]
